#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
  echo "This command must be run as root" 1>&2
  exit 1
fi

if [ -n "$1" ];then
  openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 4096
else
  cat $1 > /etc/letsencrypt/ssl-dhparams.pem
fi
