#!/usr/bin/env bash
# https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04
# https://cipherli.st/
# https://scotthelme.co.uk/a-plus-rating-qualys-ssl-test/

if [ "$(id -u)" != "0" ]; then
  echo "This command must be run as root" 1>&2
  exit 1
fi

DOMAIN="$1"
ROOT_PATH="$2"

FQDN=$(awk 'BEGIN {FS=".";OFS="."}{ print $(NF-1), $NF}' <<<$DOMAIN)
DNS_IP=$(dig @$(dig $FQDN NS +short | head -n 1) $DOMAIN +short)

if [ -n "$DNS_IP" ]; then
  if ip a | grep $DNS_IP >>/dev/null; then
    echo "SUCCESS: $DOMAIN points to this machine."
  else
    echo "ERROR: There's a DNS record for $DOMAIN but it doesn't point to this machine."
    exit 1
  fi
else
  echo "ERROR: There's no DNS record for $DOMAIN."
  echo "First add a DNS record for $DOMAIN"
  exit 1
fi
DNS_WWW_IP=$(dig www.$DOMAIN +short)
SET_WWW=
if [ -n "$DNS_WWW_IP" ]; then
  if ip a | grep $DNS_WWW_IP >>/dev/null; then
    echo "SUCCESS: www.$DOMAIN points to this machine."
    SET_WWW=YES
  else
    echo "WARNING: There's a DNS record for www.$DOMAIN but it doesn't point to this machine."
    SET_WWW=NO
  fi
else
  echo "WARNING: There's no DNS record for www.$DOMAIN."
  SET_WWW=NO
fi

if [ -z "$ROOT_PATH" ]; then
  ROOT_PATH="/var/www/$DOMAIN"
  [ -d "$ROOT_PATH" ] || mkdir -p "$ROOT_PATH"
  [ -f "$ROOT_PATH/index.html" ] || echo "Hello World!" >"$ROOT_PATH/index.html"
fi

rm -f /etc/nginx/sites-{available,enabled}/default /etc/nginx/sites-{available,enabled}/$DOMAIN /etc/nginx/sites-{available,enabled}/www.$DOMAIN
if [ "$SET_WWW" == "YES" ]; then
  cat /var/lib/ssl_setup/nginx_www.template >/etc/nginx/sites-available/www.$DOMAIN
  sed -i -e "s/{{DOMAIN}}/$DOMAIN/" /etc/nginx/sites-available/www.$DOMAIN
  sudo ln -s /etc/nginx/sites-available/www.$DOMAIN /etc/nginx/sites-enabled/www.$DOMAIN
  DOMAINS="--domains $DOMAIN,www.$DOMAIN"
else
  DOMAINS="--domain $DOMAIN"
fi
cat /var/lib/ssl_setup/nginx.template >/etc/nginx/sites-available/$DOMAIN
sed -i -e "s/{{DOMAIN}}/$DOMAIN/" -e "s|{{ROOT_PATH}}|$ROOT_PATH|" /etc/nginx/sites-available/$DOMAIN
sudo ln -s /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/$DOMAIN

letsencrypt -n --nginx $DOMAINS
letsencrypt enhance $DOMAINS --cert-name $DOMAIN --hsts --redirect --non-interactive --must-staple --staple-ocsp --nginx

sed -i -e "s/443 ssl /443 ssl http2 /g" -e "s/443 ssl;/443 ssl http2;/g" /etc/nginx/sites-enabled/$DOMAIN
[ "$SET_WWW" == "YES" ] && sed -i -e "s/443 ssl /443 ssl http2 /g" -e "s/443 ssl;/443 ssl http2;/g" /etc/nginx/sites-enabled/www.$DOMAIN

systemctl restart nginx

dig caa $DOMAIN | grep letsencrypt.org >>/dev/null || echo "WARNING : Add CAA record on your DNS server"

echo "Go to https://www.ssllabs.com/ssltest/analyze.html?d=$DOMAIN&latest=yes to check rating"
